### ISSUE TITLE
Aligned face is keeping slight shaking

### ISSUE THREAD

**Issue by yiouyou** [iperov/DeepFaceLive#105]
Hi,

Tried both DeepFaceLive_NVIDIA_10_18_2022 and DeepFaceLive_NVIDIA_11_01_2022, both of them works well, but the aligned face is keeping slight shaking, which cause the swapped face keeping shaking, even when the person remain still, not moving at all.

Any idea or advices about how to limit the shaking effect?

btw, Align mode is "From points", and if choose other align modes, the results are much worse.

Best and Thanks!

**Comment by iperov** [comment]
read faq
