### ISSUE TITLE
Why can I only see 4 cameras and how can I fix it

### ISSUE THREAD

**Issue by yier2333** [iperov/DeepFaceLive#106]
![image](https://user-images.githubusercontent.com/10252024/207009818-87ee3530-2239-4251-a891-1b464a199074.png)

**Comment by iperov** [comment]
you are using old version
download latest version

**Comment by yier2333** [comment]
> you are using old version download latest version

where can i get the  latest version bat file

**Comment by yier2333** [comment]
> you are using old version download latest version

I can't open these two links

![image](https://user-images.githubusercontent.com/10252024/207013847-77796e21-0458-43d6-8387-6d5169e35819.png)

**Comment by yier2333** [comment]
> you are using old version download latest version

Can I compile the code myself? I want to do some other image processing at the same time
