### ISSUE TITLE
Could you add Snapcamera clone or add TikTok filters to deepfacelive that you would use before or after the deepfake because Snapcamera is going away and it would be useful to make better and cooler deepfakes and cooler deepfacelive webcams  

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#115]
Is there any big updates to deepfacelive you can share about because it would be cool to have Snapchat like filters on camera source and also have to ability to put them after or before the deepfake because the filter idea would be cool because or Snapcamera going away  and also has big bugs on AMD gpus and stuff and then that would also add another type of filter people could make for deepfacelive to make it more realistic and also this could also make it so people could still use Snapchat type filters even if they didn't want to use the deepfake part and also could you add the ability to have stream integration like if something happens then this face or filter gets activated or the preset with a specific face and filter gets activated and you might still be able to make snap studio which people use to make Snapchat filters work or you could add your own type which would be harder if you could do the Snapchat way and also there is this guy that Is backing up all Snapchat filters people enable using has Snapcamera mod and also you could probably use his Snapcamera filter backups if he lets you and then all you would need to do is make the work before and after a deepfake on deepfacelive and also make them work with and then deepfacelive can turn into more then just dfm models and images

**Comment by iperov** [comment]
no
