### ISSUE TITLE
Is there a way to run deepfacelive on AMD gpu on Linux and if so is it better then running deepfacelive on windows using AMD and also is running deepfacelive using wsl2 better then running using the directx 12 version on windows because I want to use it in windows but get the best performance even if it requires wsl2

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#117]
Is there a way to run deepfacelive on AMD gpu on Linux and if so is it better then running deepfacelive on windows using AMD and also is running deepfacelive using wsl2 possible and if so is it better then running using the directx 12 version on windows because I want to use it in windows but get the best performance even if it requires wsl2

**Comment by iperov** [comment]
no
