### ISSUE TITLE
Why do I have this error? Internet connection is normal

### ISSUE THREAD

**Issue by EugenSoft** [iperov/DeepFaceLive#119]
Previously replaced faces, everything turned out. With different masks. Now it has begun to knock out such an error and the text has changed when it is turned on.
What needs to be done to fix this, please tell me
![Screenshot_1](https://user-images.githubusercontent.com/122694564/212490195-56bdbad8-0b7b-477a-9ef7-eef0a77e3159.png)
![Screenshot_2](https://user-images.githubusercontent.com/122694564/212490198-518708b7-ae92-4524-91f4-55bad97a65fc.png)

**Comment by iperov** [comment]
place deepfacelive to root of C or D
