### ISSUE TITLE
Huge Delay

### ISSUE THREAD

**Issue by vintaclectic** [iperov/DeepFaceLive#123]
Everything is setup, works great. Only issue, huge delay even with audio offset sync, and fiddling with settings...I can't seem to find solution. Could it be an issue with my paging file allocation? I mean I changed it to 32gb as suggested, but for some reason I am only getting like 10fps on the source feed from my cam and its set to auto..I tried changing it to 30fps and others but it's stuck on 10fps. All the info I really have atm, but great app so far! Please advise of any suggestions.

Thanks,
B. Justice

**Comment by iperov** [comment]
delay is not fps

delay is the time between input frame from camera and output to window.

Target delay is additional delay to match desired delay, for example 500ms.

Set audio delay in OBS to the same as target to get synced stream.

if your camera has < 30fps output, reduce exposure in dshow settings.

**Comment by vintaclectic** [comment]
Understood. Thanks for your quick reply and help! Still having issues, I am actually low on disk space on my C drive where its operating...lower than the requested 32gb+ paging file so I assume that could make a huge difference, as well? changing exposure did not help.
