### ISSUE TITLE
Attribute Error Message

### ISSUE THREAD

**Issue by heyxur** [iperov/DeepFaceLive#124]
Trying to re-download deepfacelive and every time i try to run the batch file after unzip it gives be this error message " AttributeError: module "cv2' has no attribute gapi
Press any key to continue"
i've tried deleting it and reinstalling but the same thing happens. tried restarting my computer and everything. what could be the issue?
![CCF3D03F-0C6A-4310-AA23-5582D08AF420](https://user-images.githubusercontent.com/123373148/214031574-418fb90a-759a-49e4-b90a-5504426e67ed.png)

**Comment by iperov** [comment]
move folder to C:\ root

try previous version
