### ISSUE TITLE
macOS error

### ISSUE THREAD

**Issue by pedrorenan** [iperov/DeepFaceLive#128]
I am trying to ru in macOS, but I get this error:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.`

**Comment by iperov** [comment]
i don't support macos

**Comment by pedrorenan** [comment]
It worked fine in macOS running windows on parallels desktop.
