### ISSUE TITLE
Can you add Spout2 Support because Spout2 support is way more useful then gstreamer 

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#130]
Can you add Spout2 Support because Spout2 support is way more useful then gstreamer because with spout2 you can have it input spout2 into deepfacelive then have it output back into the same spout2 use no extra resources when wanting to record or capture it as a webcam input on discord or have it work in obs https://github.com/leadedge/Spout2
https://github.com/Off-World-Live/obs-spout2-plugin this would be a cool update instead of the normal updates to this program which is more faces and update dependencies and stuff and a lot of those faces in the program i got before they where even added to deepfacelive by you

**Comment by iperov** [comment]
not bad but i have no time for that.
