### ISSUE TITLE
直接下载源码？如何运行呢？

### ISSUE THREAD

**Issue by zhangziliang04** [iperov/DeepFaceLive#131]
我的操作指令：python  main.py 信息提示：
<img width="618" alt="image" src="https://user-images.githubusercontent.com/646709/217437524-bdc676cc-baee-463e-ab19-8d2f3180c001.png">

输入参数：python main.py run ? 不好使啊，请教版主，如果要从源码运行，如何操作，main.py 应该传入什么参数？

**Comment by agchaowanhui** [comment]
这个在文档里是有的，我给你一个我的参数 python main.py run DeepFaceLive --userdata-dir /data/

**Comment by zhangziliang04** [comment]
@agchaowanhui 非常感谢，我主要是没看到文档所在的位置。我的微信：zhangziliang04 保持交流，谢谢。
