### ISSUE TITLE
Not working since 2/23

### ISSUE THREAD

**Issue by khelgor** [iperov/DeepFaceLive#138]
Hey guys,
Deepfacelive isnot working for me since yesterday, used it since months without any problem. I tried reseting settings, downloaded the new version, testing on another PC, nothing.
I can launch it, it detect my webcam, but when i select a face, I have nothing in the swapped face/merged frame windows. 
Anyone got problems too ?

I don't remember if i was using gpu or cpu, but cpu show no error, so it should work anyway.
Anyway, I noticed i have to use cpu for face swapper, because it show an error message with my 3070ti
D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded.

**Comment by iperov** [comment]
all works fine

**Comment by khelgor** [comment]
Ok but why closing the topic ? maybe some ppl could have this issue and i'm still working on resolving it
