### ISSUE TITLE
Error while running ./start.sh in Debian 11

### ISSUE THREAD

**Issue by alinciuca** [iperov/DeepFaceLive#140]
#0 24.50 ERROR: Cannot install onnx==1.13.0, onnxruntime-gpu==1.12.1 and protobuf==3.20.1 because these package versions have conflicting dependencies.
#0 24.50 
#0 24.50 The conflict is caused by:
#0 24.50     The user requested protobuf==3.20.1
#0 24.50     onnxruntime-gpu 1.12.1 depends on protobuf
#0 24.50     onnx 1.13.0 depends on protobuf<4 and >=3.20.2
#0 24.50 
#0 24.50 To fix this you could try to:
#0 24.50 1. loosen the range of package versions you've specified
#0 24.50 2. remove package versions to allow pip attempt to solve the dependency conflict
#0 24.50 
#0 24.50 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:13
--------------------
  11 |     
  12 |     RUN python -m pip install --upgrade pip
  13 | >>> RUN python -m pip install onnxruntime-gpu==1.12.1 numpy==1.21.6 h5py numexpr protobuf==3.20.1 opencv-python==4.7.0.68 opencv-contrib-python==4.7.0.68 pyqt6==6.4.0 onnx==1.13.0 torch==1.10.0 torchvision==0.11.1
  14 |     
  15 |     RUN apt install -y libnvidia-compute-$NV_VER
--------------------
ERROR: failed to solve: process "/bin/sh -c python -m pip install onnxruntime-gpu==1.12.1 numpy==1.21.6 h5py numexpr protobuf==3.20.1 opencv-python==4.7.0.68 opencv-contrib-python==4.7.0.68 pyqt6==6.4.0 onnx==1.13.0 torch==1.10.0 torchvision==0.11.1" did not complete successfully: exit code: 1
access control disabled, clients can connect from any host
Unable to find image 'deepfacelive:latest' locally
docker: Error response from daemon: pull access denied for deepfacelive, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by iperov** [comment]
tell me if you fix it

**Comment by valador** [comment]
onnx==1.13.0 need protobuf>=3.20.2 but you install protobuf==3.20.1
