### ISSUE TITLE
you should update yolov5 to yolor or yolov7 for more efficient face detection

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#145]
you should update yolov5 to yolor or yolov7 for more efficient face detection https://github.com/WongKinYiu/yolor https://github.com/WongKinYiu/yolov7 use whatever version of either one is the most efficient and works the best.

**Comment by iperov** [comment]
your links are not face models

**Comment by Pickymarker** [comment]
is this better https://github.com/PINTO0309/PINTO_model_zoo
