### ISSUE TITLE
you should update yolov5 to yolov7 

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#146]
you should update yolov5 to yolov7  https://github.com/derronqi/yolov7-face and this has a 640 model which deepfacelive i think needs all it needs is to be converted from .pt to onnx

**Comment by iperov** [comment]
no I should not

**Comment by iperov** [comment]
v7 will give no boost at the same flops

v5:
![firefox_2023-04-09_15-22-25](https://user-images.githubusercontent.com/8076202/230769655-73e93e51-7320-4650-87dd-b5780bf2e138.png)

v7:
![firefox_2023-04-09_15-22-10](https://user-images.githubusercontent.com/8076202/230769659-733d49ff-c574-4cc9-9aca-cc0e6930a2c1.png)

also converting to onnx is hard manual job

**Comment by iperov** [comment]
anyway there is no significant boost to spend the time for this.

YoloV5 is very good for real time apps

**Comment by Pickymarker** [comment]
is there any improvements that can do done to deepfacefacelive for amd becuase amd needs more improvement on deepfacelive it can get get but is not getting i would like opencl with hsa compute if not then directml if not also then here are the models someone posted on baidu  https://pan.baidu.com/s/1oIj3QgOohKpHGwJDxNvDsw#list/path=%2Fsharelink3574865391-188501854105692%2Fonnx_havepost_models&parentPath=%2Fsharelink3574865391-188501854105692
