### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by nanafy** [iperov/DeepFaceLive#147]
1. Is it possible to swap two faces on stream with different dfm models? I see that we can swap all faces or choose which face ID to track, so would it not be possible to do two live swaps if gpu can support it?

2. The name of the models that come pre-baked into the application, cannot be named differently. Since the UI keeps trying to download them if the name is not the default. Any way to overcome this?

Thanks for your help and awesome app+ui.

**Comment by iperov** [comment]
1. no direct support
2. cannot understand question

**Comment by nanafy** [comment]
1. That would be awesome. Maybe in a few years when I catch up in terms of dev, I will attempt it, lmao
2.  The model names that come with the program, for example: "Kim_Jarrey", if you try and rename the .dfm file, you cannot. If you rename the file, it thinks the model is missing and redownloads it. I guess I would have to edit the core files of the app to alter that behavior.

**Comment by iperov** [comment]
face palm

**Comment by nanafy** [comment]
Damn, I got face palmed. I guess its trivial. I appreciate the fast replies though! Take care
