### ISSUE TITLE
Did you just lock my Intellectual Property into your website?

### ISSUE THREAD

**Issue by Zxen1** [iperov/DeepFaceLive#149]
Hey, me again. You didn't just ignore my question and lock my information away with no way for me to access it, did you?
I just posted a link to my work. I thought it would have made you happy. Plus I had a question. But you seem to have ignored it and dishonourably locked it out. Unless it was an accident and you are preparing a response, we're enemies now. In which case you'd better delete my glorious work out from under your ungrateful boot. Your move.

**Comment by iperov** [comment]
issues for code issues, not for discussion

**Comment by Zxen1** [comment]
Fine, delete it then. Don't leave gallery items that people are proud of in the frickin wastebasket like garbage.
