### ISSUE TITLE
SourceCamera freezes when building with Pytorch 2.0

### ISSUE THREAD

**Issue by factoryofthesun** [iperov/DeepFaceLive#152]
Hi thank you for the great work. I've tried building the software on Windows 11 w/ GTX 1060 but with updated torch (2.0.0) and torchvision versions (0.15.0) on CUDA 11.8, and now the source camera stream freezes. Any advice?

**Comment by iperov** [comment]
DeepFaceLive does not use pytorch, only dlls from the build.
Also cuda does not affect your camera.
