### ISSUE TITLE
Feature Request: Add External Streamer.bot/ SAMMI Control to all of Deepfacelive Stuff

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#156]
yeah it would be it be cool if everything on deepfacelive was able to be controlled externally with streamer.bot or SAMMI so that you can have other programs or devices be able to go enable a specific filter with one click of a button say like a stream deck or launchpad or live stream chat instead of having to scroll through all the faces to click on it when you want quick dfm change or to have it auto change based on a function

**Comment by iperov** [comment]
cool

**Comment by Pickymarker** [comment]
so thats a no
