### ISSUE TITLE
RTX3070 Mobile GPU = low performance?

### ISSUE THREAD

**Issue by OnlyStopOnTop** [iperov/DeepFaceLive#159]
Hello,

I downloaded dfl for nvidia and tried to use it, but as soon as I start it I do only get 1-2 images of my webcam in the dfl software?

It kinda looks like it has issues with rendering it, it is not responding quickly and does not show any "video" just 1-2 frames and only for camera source.

I do use a laptop with tx3070, ryzen 9 and 16gb of ram.

Is my performance to low for using this software? Or are there any hidden settings to improve?

**Comment by davidlorex** [comment]
Did you try expanding your virtual memeory upto 32gb also check that you have your Graphics card driver updated .

**Comment by OnlyStopOnTop** [comment]
test

**Comment by OnlyStopOnTop** [comment]
> Its not clear what you mean " its not showing any video, you can rephrase and make it more clear.
> **It´s not showing any video. Just 1-2 frames in the camera section - that´s it. It looks like there are some performance issues - tahts the reason I´m wondering because I use rtx 3070 and ryzen 9 hardware.**
> For the slow performance. Did you try expanding your virtual memeory upto 32gb also check that you have your Graphics card driver updated .

**I added my virtual ram to 12-32gb in my windows 11 settings. But since I changed it the software does not pop up anymore. It is starting but the main windows is just not appearing?**
