### ISSUE TITLE
cannot find module  xlib.image.misc

### ISSUE THREAD

**Issue by hepytobecool** [iperov/DeepFaceLive#16]
i clone the code and try to run on pycharm and find there is no module xlib.image.misc
![image](https://user-images.githubusercontent.com/32845040/132478666-434fc05a-28d3-4555-b63f-c054fefc5e67.png)

**Comment by iperov** [comment]
I don't support your custom experiments with the code.
Download official prebuilt windows folder.

**Comment by hepytobecool** [comment]
> I don't support your custom experiments with the code.
> Download official prebuilt windows folder.

ok, thank you

**Comment by michaeldanner** [comment]
> 
> 
> > I don't support your custom experiments with the code.
> > Download official prebuilt windows folder.
> 
> ok, thank you

You can solve this by replacing some code in xlib/image/__init__.py

Replace from .misc import get_NHWC_shape
by 
def get_NHWC_shape(img):
    N, H, W, C = img.shape
    return N, H, W, C
