### ISSUE TITLE
Unable to use OBS Virtual Camera as camera source

### ISSUE THREAD

**Issue by VegetableChichen** [iperov/DeepFaceLive#160]
## 无法使用OBS虚拟摄像机作为摄像机源
我使用“直播源”＋“PotPlayer”＋“OBS虚拟摄像机”的方式，搭建了我的虚拟摄像机，但是它无法在“DeepFaceLive”→“摄像机源”中正常播放使用。
无论我改变“OBS虚拟摄像机”或者“摄像机源”的分辨率、帧率，或是把两者调成一致，都无法正常使用。
OBS版本：27.2.4，DeepFaceLive版本：NVIDIA_build_05_04_2023。

---------------------------------------------------------------------

# Google Translate:

## Unable to use OBS virtual camera as camera source

I built my virtual camera by using "Live Source" + "PotPlayer" + "OBS Virtual Camera", but it cannot be played normally in "DeepFaceLive" → "Camera Source".
No matter if I change the resolution and frame rate of "OBS Virtual Camera" or "Camera Source", or adjust the two to be consistent, it still cannot work normally.
OBS version: 27.2.4, DeepFaceLive version: NVIDIA_build_05_04_2023.

--------------------------------------------------------------------

# Screenshot

![Snipaste_2023-05-27_22-55-57](https://github.com/iperov/DeepFaceLive/assets/87602241/ca874f82-3425-4ac1-9b2c-958cbc16a6d2)
---------------------------------------------------------------
![Snipaste_2023-05-27_22-58-57](https://github.com/iperov/DeepFaceLive/assets/87602241/4a9c1715-8026-4f1b-9b36-7fa668189065)

**Comment by lyl-94** [comment]
Why was this issue closed? I'm also experiencing the same problem.
