### ISSUE TITLE
ubuntu/linux compatibility?

### ISSUE THREAD

**Issue by humandotlearning** [iperov/DeepFaceLive#17]
can the project work on ubuntu/linux environment?  if so, could you point me to the doc or how could i help to port.

**Comment by justinjohn0306** [comment]
> can the project work on ubuntu/linux environment? if so, could you point me to the doc or how could i help to port.

You can get in touch with me and close this issue

**Comment by eVen-gits** [comment]
Please, once you have this down, don't forget to publish the procedure. It would be very helpful.

Furthermore, does this require CUDA capable GPU, or can this also run on AMD cards?

**Comment by omarcevi** [comment]
> can the project work on ubuntu/linux environment? if so, could you point me to the doc or how could i help to port.

were you able to run it on a linux enviroment?

**Comment by eVen-gits** [comment]
> were you able to run it on a linux enviroment?

No, I did not.

**Comment by iperov** [comment]
https://github.com/iperov/DeepFaceLive/tree/master/build/linux

**Comment by lolz0r** [comment]
@iperov Cool, but what is the proper camera input? (none seem to work)

**Comment by baixinping618** [comment]
> > 该项目可以在 ubuntu/linux 环境下运行吗？如果是这样，您能否将我指向文档或我如何帮助移植。
> 
> 您可以联系我并关闭此问题

Did you successfully run deepfacelive on linux?

**Comment by charlielito** [comment]
With todays PR https://github.com/iperov/DeepFaceLive/pull/50 now it should work:
Run it with: ` ./start.sh -c`
