### ISSUE TITLE
Keep having files missing after downloading the Master file.

### ISSUE THREAD

**Issue by IamFame88** [iperov/DeepFaceLive#172]
I’m stuck at “from xlib import appargs as lib_appargs
ModuleNotFounderror: No module named ‘xlib’
In the command prompt when running the install. What I noticed is that the source files I downloaded from GitHub contains a little less that what is listed here, I have no Xlib folder amongst my files… I don’t know if that’s a factor… can anyone please help with a solution.

**Comment by Pros12am** [comment]
Okay that's not much of a problem could handle that mine if working

**Comment by elvisoge** [comment]
am having similar issue. how did you fix it
