### ISSUE TITLE
Webcam FPS is very low in latest Nvidia release.

### ISSUE THREAD

**Issue by hoolswelsh** [iperov/DeepFaceLive#174]
Since updating to the latest version, and the older version available in the mega link, webcam FPS is much lower than in previous versions. With older versions of the software I could run 1080p with the webcam module reporting 30fps continuously now I only get 24fps using the 640x480 preset.

**Comment by BbChip0103** [comment]
@hoolswelsh can you share your old version? I face same issue, and I'm trying to fix this
