### ISSUE TITLE
how do you fix this on deepfacelive

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#176]
how do you fix this on deepfacelive when using gpu on face merger it shows black dots but not when using  cpu as face merger and this still happens even after reinstalling gpu driver and using the previous version of deepfacelab 
![image](https://github.com/iperov/DeepFaceLive/assets/74084396/954fa3d4-3356-4db7-8860-464bc5ab7b5d)

**Comment by iperov** [comment]
it's linux issue

**Comment by Pickymarker** [comment]
i'm on windows 10
