### ISSUE TITLE
How do you fix this on Deepfacelive Windows 10

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#177]
when using gpu on face merger it shows black dots but not when using  cpu as face merger and this still happens even after reinstalling gpu driver and using the previous version of deepfacelab 
![image](https://github.com/iperov/DeepFaceLive/assets/74084396/0a048028-a54e-4171-8e05-62567c7f09a1)
And i'm using Windows 10 fully up to date with a amd gpu using directx 12 version of deepfacelive

**Comment by iperov** [comment]
already answered.
One more - you will be banned

**Comment by iperov** [comment]
ok. It is not mass problem.
if you fix it, let me know.

**Comment by iperov** [comment]
it is not reproducible
you will get no help

**Comment by Pickymarker** [comment]
okay so it's not reproducible on windows 10 with a amd gpu

**Comment by iperov** [comment]
how do you think I should it reproduce?
