### ISSUE TITLE
Questions: AI accelerator card

### ISSUE THREAD

**Issue by AlexNikMak** [iperov/DeepFaceLive#182]
Hello everyone, I’m quite new to this topic, so forgive me in advance if the question is posted in the wrong way or is off topic.

I'm wondering if it's possible to use M.2 Accelerator with Dual Edge TPU(https://coral.ai/products/m2-accelerator-dual-edgetpu/) instead of or together with a regular video card. Also, will this bring a performance increase or will it significantly reduce the use of the video card? Or will replace it altogether. This question interests me greatly since these devices are relatively inexpensive compared to video cards.

Thank you very much for your answer.

**Comment by iperov** [comment]
onnxruntime does not support tpu's

**Comment by iperov** [comment]
also tpu from link is only for int8.
Deepfake requires float32

**Comment by AlexNikMak** [comment]
Thanks for your reply. 
In this case, maybe you know a way to improve performance other than purchasing a more powerful video card, or is this the only way?
