### ISSUE TITLE
face detector always turn off on deepfacelive DirectX12 build

### ISSUE THREAD

**Issue by Bold0077** [iperov/DeepFaceLive#183]
hello Guys 
please I have issues with my Deepfacelive ,each time I turn face detector it always turn off 
directx12 build
I'm using Intel i5 4210U

GPU : Intel (R) HD Graphics Family

**Comment by iperov** [comment]
some error. Use cpu or other gpu.

**Comment by Currency1r** [comment]
> hello Guys 
> please I have issues with my Deepfacelive ,each time I turn face detector it always turn off 
> directx12 build
> I'm using Intel i5 4210U
> 
> GPU : Intel (R) HD Graphics Family

Hey bro

**Comment by Bold0077** [comment]
Hello thanks for your response today

But please how can I add my own photos on the face swapper models ?
