### ISSUE TITLE
not working on AMD GPU

### ISSUE THREAD

**Issue by f1am3d** [iperov/DeepFaceLive#186]
After following the instructions and selecting a video file, the application stops working. It responds to inputs, but does not detect faces, swap them, or play the video. 

OS: Windows 11
GPU: RX 7900 XTX 24Gb (latest drivers)

**Comment by iperov** [comment]
cool
let me know if you fix it

**Comment by f1am3d** [comment]
> cool let me know if you fix it

Ah, you do "solve" bugs just by closing tickets? I can see why this garbage doesn't work 😁

**Comment by iperov** [comment]
which bug? you can only say it's not working. There could be a million reasons.
