### ISSUE TITLE
Spout instead of window capture

### ISSUE THREAD

**Issue by aximut** [iperov/DeepFaceLive#29]
Hi,
first off, this is so cool, thanks for your marvellous work!

This is more of a suggestion than an issue.
When I saw your excellent pipeline, the extent on how this is all optimized to run in real time and the ease of configurability, I was wondering if you know of [Spout](https://github.com/leadedge/Spout2).
It could save some resources to just output the final stream as a `SpoutSender`. This could then easily be imported into OBS by the [Spout Plugin](https://github.com/Off-World-Live/obs-spout2-plugin).
The advantage would be that all the buffers already in the GPU would get directly transferred to OBS and not via a window capture.

**Comment by iperov** [comment]
I prefer more portable system and keep less dependencies as possible.
Capture window by OBS is fine solution.
