### ISSUE TITLE
Trained Model cannot be imported

### ISSUE THREAD

**Issue by wp2333** [iperov/DeepFaceLive#3]
Thanks for your sharing of your wonderful work!
But I get some trouble when using. Hope you can give some help. Thank you very much!
I cannot import trained dfl model by click the 'select' button in Face swapper.
Actually, I can find my model by the small eye on the right.
So I think mybe the structure of my model files is not correct. But I dont know how to fix it. 
My folder is as following:
![image](https://user-images.githubusercontent.com/52447492/126858683-6f33eb5f-8ebc-4a3e-b86a-4e10df60fe29.png)

**Comment by iperov** [comment]
where do you see dfm models?

**Comment by Erickrus** [comment]
@iperov : I use "export SAEHD as dfm" model, but the size is very small around 321M, while the one used in DeepFaceLive 685M. How to prepare the dfm model ?
