### ISSUE TITLE
Settings for the supplied models

### ISSUE THREAD

**Issue by Labbers** [iperov/DeepFaceLive#31]
What settings and resolution are the ready-to-use public face models created with? 
Is the resolution better than the user-faq supplied settings "res:224, WF, archi:liae-udt, ae_dims:512, e_dims:64, d_dims:64, d_mask_dims:32, eyes_mouth_prio:Y, blur_out_mask:Y, uniform_yaw:Y, lr_dropout:Y, batch:8. Others by default"? 

And whats the difference with the Google FaceMesh models, is there any code for that?

**Comment by iperov** [comment]
settings in faq.
Google FaceMesh is used for face landmarks.

**Comment by Labbers** [comment]
Do you have any recommendations for higher resolution models? For example, 512x512 on a 24g GPU.
