### ISSUE TITLE
ONNXRuntimeError

### ISSUE THREAD

**Issue by F1uk369** [iperov/DeepFaceLive#33]
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:331 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 150994944

Selected my GPU, 1660 super in the face swapper section, this errors out.

**Comment by iperov** [comment]
not enough vram , read faq
