### ISSUE TITLE
Do RTM training need dst to be xsed'ed?

### ISSUE THREAD

**Issue by fient0989** [iperov/DeepFaceLive#34]
I training with RTM model for the first time
I'm wondering should the dst(rtm wf faceset in the torrent) be xseg and apply?
In the FAQ it only said that i should xseg and apply in src but don't known should it be apply in dst

**Comment by iperov** [comment]
rtm from torrent already generic xsegged

**Comment by notname956** [comment]
i can't extract the faceset.pak
