### ISSUE TITLE
How to use deepfacelive on linux

### ISSUE THREAD

**Issue by baixinping618** [iperov/DeepFaceLive#36]
How to use deepfacelive on linux

**Comment by iperov** [comment]
there is no official setup tutorial, because I don't use linux

**Comment by iperov** [comment]
look at https://github.com/iperov/DeepFaceLive/tree/master/build/linux

**Comment by baixinping618** [comment]
Thank you, but I keep failing when building the image. Do you have a built image?

**Comment by baixinping618** [comment]
> 看看https://github.com/iperov/DeepFaceLive/tree/master/build/linux

Thank you, but I keep failing when building the image. Do you have a built image?

**Comment by iperov** [comment]
as I said, I don't use linux

**Comment by baixinping618** [comment]
> as I said, I don't use linux

hi, I read the linux code, but I still need to use the QT interface, right? I want to run it on linux without an interface. Do you have any code without the qt interface?
