### ISSUE TITLE
Installer Download Time-Out

### ISSUE THREAD

**Issue by LanceMcCarthy** [iperov/DeepFaceLive#39]
Hi Team,

The mega.nz download link isn't working (it times out). Has the installer been moved?

**Comment by LanceMcCarthy** [comment]
Quick Update, this is likely a mega.nz site issue rather than a specific blob's storage issue. None of Mega's endpoints are working, even https://mega.nz/sdk times out.

**Comment by Arthurzhangsheng** [comment]
download it from here [release page](https://github.com/iperov/DeepFaceLive/releases)

**Comment by LanceMcCarthy** [comment]
Other than AudioRepeater.exe, I don't see an installer/executable on the Releases page.

**Comment by iperov** [comment]
looks like mega-nz is available in not all countries

**Comment by LanceMcCarthy** [comment]
Aha! Okay, now that we know the root cause, a VPN can workaround the issue. Thanks!

What country do you recommend I tunnel to?

**Comment by iperov** [comment]
i don't know, try various vpn
