### ISSUE TITLE
请问deepfacelive可以在换脸的同时将头发一起更换吗，请看这个例子   https://www.youtube.com/watch?v=xr5FHd0AdlQ

### ISSUE THREAD

**Issue by baixinping618** [iperov/DeepFaceLive#40]
请问deepfacelive可以在换脸的同时将头发一起更换吗，请看这个例子   https://www.youtube.com/watch?v=xr5FHd0AdlQ

**Comment by Arthurzhangsheng** [comment]
no
不会

**Comment by baixinping618** [comment]
> no 不会

So why does this video seem to be able to change hair

**Comment by iperov** [comment]
yes. Train HEAD model 320res
