### ISSUE TITLE
Use VDO.Ninja as a Camera Source?

### ISSUE THREAD

**Issue by pjh4** [iperov/DeepFaceLive#44]
I use my phone's camera as a virtual camera for my PC via OBS using https://vdo.ninja/

Is it possible to use this virtual camera as a Camera Source?

**Comment by iperov** [comment]
if you are programmer, you can investigate how it works

goal - write a pure test code in python that can receive raw frames. 

Then I can include it to DFLive easily.

**Comment by pjh4** [comment]
Thanks for your response. Turns out it was an OBS related issue not outputting the virtual camera as DirectShow.

I was able to resolve this by installing OBS Virtualcam 2.0.5

https://obsproject.com/forum/resources/obs-virtualcam.949/
