### ISSUE TITLE
Автор, как изменить разрешение источника видео, хочу добиться характеристик мобильного телефона прямой трансляции, 720х1280

### ISSUE THREAD

**Issue by LAON7877** [iperov/DeepFaceLive#49]
Автор, как изменить разрешение источника видео, хочу добиться характеристик мобильного телефона прямой трансляции, 720х1280

**Comment by iperov** [comment]
в текущей гитхаб версии исправлен ресайз видео с камеры. Релиз в ехе будет не скоро.
