### ISSUE TITLE
Use DeepFaceLive's dfm model from the command line to instantly swap faces in any video file

### ISSUE THREAD

**Issue by tradenity** [iperov/DeepFaceLive#51]
Hi

I'd like to know if there is a python script or example code that can invoke DeepFaceLive from the command line.
I Know that this functionality is available in deepfacelab but as far as I know deepfacelive has 2 main advantages:
1- It can work with any target video
2- It is real time fast (30 fps is possible)

So I'd like to know how to load dfm model and point deepfacelive to a video file to instantly convert it.
Is there any script (python of course) or example code that can do this

Thanks

**Comment by iperov** [comment]
https://github.com/iperov/DeepFaceLive/blob/master/doc/user_faq/user_faq.md#i-want-to-have-more-control-when-changing-faces-in-a-video-will-the-new-functionality-be-implemented
