### ISSUE TITLE
How to use Xseg-dst

### ISSUE THREAD

**Issue by nexon33** [iperov/DeepFaceLive#63]
I have made a model and using xseg I have excluded the mouth when open and trained it, and it masks as desired. But when I export this model to dfm and use it in deepfacelive the mouth is not excluded. I can however use deepfacelabs merge SAEHD and set mask_mode to Xseg-dst. This gives the desired result.

Is there any way to achieve the same in deepfacelive?

**Comment by iperov** [comment]
not related to DeepFaceLive

**Comment by iperov** [comment]
generic xseg model has low performance to work in real time.

**Comment by nexon33** [comment]
> generic xseg model has low performance to work in real time.

Is there any way to still try this and see how well it does?

**Comment by iperov** [comment]
no, code it for yourself

**Comment by nexon33** [comment]
> no, code it for yourself

I took a quick look at the code but I have no idea on how to do that, can you point me in the right direction? I'm willing to pay for the modification
