### ISSUE TITLE
Configuring Project in PyCharm

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [iperov/DeepFaceLive#64]
Hello,
Thank you for sharing this wonderful work with us.

I need to configure the project in PyCharm IDE using Anaconda. 
My Basic question is
**"Can I run the whole project by typing one complete python command with command-line arguments by providing the link to the image and video. This means can I run the project by calling the main.py file only and then generate the output in a separate folder."**
OR 
**Do I need to run the DeepFaceLive.py file and then run the project from the user interface?**

Thank You

**Comment by iperov** [comment]
why do you need pycharm IDE ? do you work in Windows ?

**Comment by mayanktiwariiiitdmj** [comment]
Yes sir, and I want to configure the project so that it can run without human interaction. I have already used the **Windows Release Complete UI-based setup**. Now I want to run the project without human interaction, by simply typing one command and passing the required data and command-line arguments.

**Comment by iperov** [comment]
Why? End goal?

**Comment by mayanktiwariiiitdmj** [comment]
Sir, my end goal is to compare its results with the First Order Model [link](https://github.com/AliaksandrSiarohin/first-order-model)

**Comment by iperov** [comment]
Issue section is only for problems with deepfacelive

**Comment by iperov** [comment]
btw https://github.com/iperov/DeepFaceLive/blob/master/doc/user_faq/user_faq.md#i-want-to-change-some-code-and-test-the-result-on-my-local-machine-what-i-need-to-do

**Comment by mayanktiwariiiitdmj** [comment]
Thank you for this suggestion sir.
