### ISSUE TITLE
How to use TPFMM face animator?

### ISSUE THREAD

**Issue by rayandaod** [iperov/DeepFaceLive#70]
Hello, 

Is it possible to use TPFMM (https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model) with the latest release of DeepFaceLive for Windows? If so, how can I do?

If not, should I build the project on Linux? Is there anything that I need to do then to make this model available to choose?

Thank you,
Rayan

**Comment by iperov** [comment]
if you cannot read, I cannot write.
