### ISSUE TITLE
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:342 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 150994944

### ISSUE THREAD

**Issue by cubestudioss** [iperov/DeepFaceLive#73]
Any time I try to run the face swapper it shows this 
 [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:342 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 150994944

Can anyone help?

**Comment by cubestudioss** [comment]
![DeepFaceLive 7_22_2022 5_02_03 PM](https://user-images.githubusercontent.com/97353447/180574607-cdf3e5c9-f8e2-485b-9e06-0325626ba55f.png)
here is photo

**Comment by cubestudioss** [comment]
And it was working fine a day ago

**Comment by iperov** [comment]
low GPU mem. 

Disable other apps that can use GPU.
Use other GPU for monitor output, for example Integrated GPU in Intel processors, thus more video mem will be available.
