### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by ceeyee** [iperov/DeepFaceLive#75]
When I tried to launch the program (DeepFaceLive_NVIDIA_build_06_14_2022) for the first time, I encountered the following error:
May I know how to solve the problem? Thank you.

![image](https://user-images.githubusercontent.com/17518929/180650567-c2b6b763-a65e-4672-a3cc-c1c9dd014ea2.png)

**Comment by iperov** [comment]
copy folder to root of disk

**Comment by iperov** [comment]
what OS ? does not look like Windows 10

**Comment by ceeyee** [comment]
I copied the folder to D:\ but still had the same error.
The system is a Windows 7 64. Is there a way to make it work, for example by installing the missing DLL?
Thank you.

**Comment by iperov** [comment]
if u fix problem, let me know

**Comment by bucketcat** [comment]
I have the same issue, win10. Weird thing is that it was working for a few hours. Then re-launch, exact same error as OP. The only thing I changed was to add install of FFMPEG as path variable for another unrelated project but that can't be related. Updating Drivers, OS version or downloading older builds did not work. 

Neither did adding it to windows defender as exception, running as admin, running full CHKDSK /F /R, changing drive and path to top level directory. Very odd, I have a bunch of other projects that all compile just fine that use near identical dependencies so it's exclusive to this repo.

Any ideas to what can be causing it?

**Comment by bucketcat** [comment]
I figured out what it was. Ffmpeg install wiped my system environment path variables when it added itself LOOOL. Luckily I had a backup from a few days ago. Not sure how that happened, might be worth looking into it if its some certain windows builds that are affected.

Everything works fine now, and I've backed up my registry so that it will never be lost again lol.
