### ISSUE TITLE
crashed green output in the linux env

### ISSUE THREAD

**Issue by BbChip0103** [iperov/DeepFaceLive#77]
Hi, there. thank you for your nice work.
I use linux and windows both. (usually use linux for development and sometimes use windows for the other reason)
When I store output frame from file(.mp4) in the linux, green noise was usually occured like below
![image](https://user-images.githubusercontent.com/19839987/183237247-da3e8d12-4a22-4f99-864f-d9445b1de60a.png)
I tried this in the windows env at the same condition (same file, same options, etc), and green noise was not occured.
Has anybody face this issue?

**Comment by iperov** [comment]
Try GPU merger.
This problem is related to opencv.
I don't use linux. So if you will investigate the problem and fix it, let me know.

**Comment by BbChip0103** [comment]
Ok, I tracked this issue stage by stage. And I found something.
I was trying to track at what stage this problem exactly occurred.

![image](https://user-images.githubusercontent.com/19839987/183237573-bd2b6ae0-102c-4e24-b5a7-f7f72f7a810b.png)
1. As we see upper result by stages,  File loading, Detecting and Marking, Aligning, Generating face by swapper looks fine.

![image](https://user-images.githubusercontent.com/19839987/183237765-93777171-f18c-443a-8bc3-15df274558f4.png)
2. As we see upper result. The noise was made before merge stage. Because swapped face was overwritten on the noise.

So we need to find the bug between align stage and merge stage.

**Comment by iperov** [comment]
What res of video?

**Comment by BbChip0103** [comment]
![image](https://user-images.githubusercontent.com/19839987/183242779-89312419-426b-46f3-b19d-9a47b4ccb704.png)
Here it is. as you see.

**Comment by iperov** [comment]
what resolution of video?

**Comment by iperov** [comment]
ok i see 1024

**Comment by iperov** [comment]
keep working on it

**Comment by iperov** [comment]
@BbChip0103 no news?

**Comment by BbChip0103** [comment]
@iperov 

I have not took care of this issue because really busy work for my job.
But now I can handle this again. 
I will update this issue. Promise.
