### ISSUE TITLE
SEVERE -- WindowsBuilder.py change functionality of shutil.rmtree(release_path)

### ISSUE THREAD

**Issue by fmac2000** [iperov/DeepFaceLive#78]
Extremely dangerous, wipes a directory recursively. This stupid function nearly wiped half my hard drive. 

To any user's reading this, only build in a directory that is empty ( and make sure 100% you've not misspelt the argument).

Please update this ASAP.

**Comment by iperov** [comment]
1) https://github.com/iperov/DeepFaceLive/blob/6c7d6cb4a8684074ef3780cea448e2771df6890b/LICENSE#L593

2) you should not use code directly from repo. Use prebuilt binary.

**Comment by fmac2000** [comment]
it would take you the same amount of time it took you to respond to this thread to implement - or atleast a warning message.

**Comment by iperov** [comment]
you even don't have access to the builder from main.py
so don't go there if you don't know how it works
