### ISSUE TITLE
Empty dfm_models folder

### ISSUE THREAD

**Issue by SamArtGit** [iperov/DeepFaceLive#8]
Downloaded latest version from Mega: DeepFaceLive_build_07_24_2021.exe

![image](https://user-images.githubusercontent.com/56885075/126985993-fac67552-fb80-4b9e-8beb-69025b97c6b7.png)

![image](https://user-images.githubusercontent.com/56885075/126986007-2af6e0aa-f7e5-44e4-b40e-7ed2bc002751.png)

**Comment by iperov** [comment]
![firefox_2021-07-26_16-18-03](https://user-images.githubusercontent.com/8076202/126987343-242e20f3-c9b9-499f-b1ca-f09278a840f8.png)
