### ISSUE TITLE
DFLive Sound

### ISSUE THREAD

**Issue by raymondsim** [iperov/DeepFaceLive#84]
Hi, when I import a video for face swap in DFLive, the audio from the video is discarded. Is there any ways I can get the sounds to be played with the video?

Thanks.

**Comment by iperov** [comment]
no. transfer sound from original video using your own video editor

**Comment by raymondsim** [comment]
I also noticed that when I save output sequence from DFLive, the fps dropped sharply and combining images to video looks really strange. Is there any ways we could save the video instead? Or did I miss out any settings? Thanks.
