### ISSUE TITLE
does deepfacelive support opencl

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#88]
does deepfacelive support opencl

**Comment by Pickymarker** [comment]
and if not is there a way to get opencl support for this

**Comment by iperov** [comment]
for what ?

**Comment by Pickymarker** [comment]
for the 5700xt

**Comment by iperov** [comment]
for AMD cards, use directx version

**Comment by Pickymarker** [comment]
but why direct x when open cl would be faster if there was a version
