### ISSUE TITLE
No GPU option for Face Merger under linux

### ISSUE THREAD

**Issue by hcker2000** [iperov/DeepFaceLive#89]
I have GPU options for everything else that I should except the Face Merger.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/759902/192625857-db32db12-77cb-4792-b90e-1d56b8e61ba4.png">

**Comment by iperov** [comment]
looks like no OpenCL driver installed in linux

**Comment by iperov** [comment]
@CeeBeeEh do you know what to install for generic compatible OpenCL 1.2 ?

**Comment by CeeBeeEh** [comment]
@iperov I just created a PR (https://github.com/iperov/DeepFaceLive/pull/90) to get OpenCL support into the container. There seems to be some oddity with how Nvidia handles OpenCL in their containers. It seems they didn't even support it as of a few years ago. Technically, manually installing driver libraries in the container is not the way to go, but the fix I put in is a serviceable workaround. I'll look for a "better" solution in the meantime.

@hcker2000 I have a feeling that your host Nvidia driver is broken now. I would bet that `nvidia-smi` will not show proper output. If that's the case, try to reinstall the Nvidia drivers to get back into a working state. Just a reference for the future, for Nvidia containers all you need on the host is the Nvidia driver. Everything else (CUDA libraries, cudNN, etc) will be provided by the container itself. So as long as `nvidia-smi` gives you sane outputs, your host is good to go.

**Comment by CeeBeeEh** [comment]
Just tested on my laptop, and throwing an error "Exception: Unable to create OpenCL context" when selecting GPU under "Face merger". Will look into this further.

**Comment by iperov** [comment]
@CeeBeeEh thank you

**Comment by hcker2000** [comment]
@CeeBeeEh I went ahead and removed OpenCL and re-installed the normal drivers all good. cant wait to try this once the pull request makes it in.
