### ISSUE TITLE
expected performance with NVIDIA GeForce RTX 2060

### ISSUE THREAD

**Issue by RadW2020** [iperov/DeepFaceLive#93]
Hello, 

I have this graphic card https://www.techpowerup.com/gpu-specs/geforce-rtx-2060.c3310
![imagen](https://user-images.githubusercontent.com/8538542/194640222-b98c86b3-431e-4c80-9791-5c59f2be8893.png)

And I'm having between 9 ans 11 FPS in with deep Face Live Image Animation.

Do you think this is ok?, or should I investigate configurations to improve performance?

Cheers!

**Comment by iperov** [comment]
![firefox_2022-10-08_13-56-58](https://user-images.githubusercontent.com/8076202/194701776-5024cc43-71a4-4092-b88e-d3fdd273f32a.png)

you have only 6.4TFlops

**Comment by iperov** [comment]
by the way you can assign other modules to other GPU/CPU, and leave face animator only in 2060, perhaps you will get more FPS.
