### ISSUE TITLE
obs 27 virtual camera works with deepfacelive but obs 28 does not for some reason can you fix it

### ISSUE THREAD

**Issue by Pickymarker** [iperov/DeepFaceLive#95]
obs 27 virtual camera works with deepfacelive but obs 28 does not for some reason can you fix it

**Comment by Pickymarker** [comment]
but how do you fix it

**Comment by iperov** [comment]
cam capture is done by OpenCV module. So I don't know how to fix.

**Comment by Pickymarker** [comment]
found fix for obs 28 https://github.com/Avasam/obs-virtual-cam/releases
https://github.com/opencv/opencv/issues/19746

**Comment by HamnaAkram** [comment]
@Pickymarker I am trying to input the virtual camera stream to DFL but its not working. did try the obs 28 version with the virtual cam 3, doesnt help either.
Can you let me know which DFL version were you able to work with ?
